# fly.toml app configuration file generated for e-commerce-nic on 2025-06-23T00:00:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "e-commerce-nic"
primary_region = "mia"  # Miami region for better latency in Nicaragua

[build]

[env]
  FLASK_ENV = "production"
  FLASK_APP = "app.py"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/api/health"

[http_service.concurrency]
  type = "connections"
  hard_limit = 25
  soft_limit = 20

[[services]]
  protocol = "tcp"
  internal_port = 5000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    interval = "10s"
    grace_period = "5s"
    method = "get"
    path = "/api/health"
    protocol = "http"
    timeout = "4s"
    tls_skip_verify = false

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[deploy]
  release_command = "python init_db.py"

[mounts]
  source = "uploads_volume"
  destination = "/app/uploads"
